In [7]:
from scipy.stats import zscore

data=sns.load_dataset('iris')
df=data.copy()
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [9]:
z_scores = np.abs(zscore(df.drop('species',axis=1)))
z_scores

     sepal_length  sepal_width  petal_length  petal_width
0        0.900681     1.019004      1.340227     1.315444
1        1.143017     0.131979      1.340227     1.315444
2        1.385353     0.328414      1.397064     1.315444
3        1.506521     0.098217      1.283389     1.315444
4        1.021849     1.249201      1.340227     1.315444
..            ...          ...           ...          ...
145      1.038005     0.131979      0.819596     1.448832
146      0.553333     1.282963      0.705921     0.922303
147      0.795669     0.131979      0.819596     1.053935
148      0.432165     0.788808      0.933271     1.448832
149      0.068662     0.131979      0.762758     0.790671

[150 rows x 4 columns]

In [15]:
non_outliers = (z_scores <= 3).all(axis=1)

df_no_outliers = df[non_outliers]
df_no_outliers

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[149 rows x 5 columns]

In [17]:
(z_scores<=3)

     sepal_length  sepal_width  petal_length  petal_width
0            True         True          True         True
1            True         True          True         True
2            True         True          True         True
3            True         True          True         True
4            True         True          True         True
..            ...          ...           ...          ...
145          True         True          True         True
146          True         True          True         True
147          True         True          True         True
148          True         True          True         True
149          True         True          True         True

[150 rows x 4 columns]

In [23]:
outliers = (z_scores > 3).any(axis=1)

outlier_rows = df[outliers]
outlier_rows

    sepal_length  sepal_width  petal_length  petal_width species
15           5.7          4.4           1.5          0.4  setosa

In [27]:
from sklearn.ensemble import IsolationForest
import seaborn as sns
import pandas as pd
import numpy as np

In [29]:
data = sns.load_dataset("iris")
data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [33]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
data['species']=lb.fit_transform(data['species'])

In [39]:
data.head(4)

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0

In [41]:
clf = IsolationForest(random_state=10)
clf.fit(data)

IsolationForest(random_state=10)

In [43]:
clf.predict(data)

array([ 1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1, -1, -1, -1, -1,
        1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
        1,  1,  1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1,  1,  1,  1, -1,
        1, -1,  1,  1,  1,  1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,
        1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1,
       -1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1, -1, -1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [51]:
y_hat[y_hat==-1]

     sepal_length  sepal_width  petal_length  petal_width  species
0             NaN          NaN           NaN          NaN      NaN
1             NaN          NaN           NaN          NaN      NaN
2             NaN          NaN           NaN          NaN      NaN
3             NaN          NaN           NaN          NaN      NaN
4             NaN          NaN           NaN          NaN      NaN
..            ...          ...           ...          ...      ...
145           NaN          NaN           NaN          NaN      NaN
146           NaN          NaN           NaN          NaN      NaN
147           NaN          NaN           NaN          NaN      NaN
148           NaN          NaN           NaN          NaN      NaN
149           NaN          NaN           NaN          NaN      NaN

[150 rows x 5 columns]

In [53]:
np.where(y_hat==-1)

(array([], dtype=int64), array([], dtype=int64))